import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    borderBottomWidth: 1,
  },
  headerSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  title: {
    fontSize: 32,
    fontWeight: "700" as const,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 32,
    gap: 16,
  },
  heroCard: {
    marginTop: 18,
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
  },
  heroTitle: {
    marginTop: 8,
    fontSize: 22,
    fontWeight: '700' as const,
  },
  heroDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
  },
  heroStatsGrid: {
    marginTop: 16,
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 10,
  },
  heroStatCard: {
    minWidth: '47%',
    flexGrow: 1,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
  },
  heroStatValue: {
    fontSize: 22,
    fontWeight: '700' as const,
  },
  heroStatLabel: {
    marginTop: 4,
    fontSize: 13,
  },
  sectionGroup: {
    borderRadius: 22,
    borderWidth: 1,
    paddingVertical: 6,
    overflow: 'hidden' as const,
  },
  groupEyebrow: {
    fontSize: 12,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  groupTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    paddingHorizontal: 20,
    marginTop: 6,
  },
  groupDescription: {
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 20,
    marginTop: 8,
    marginBottom: 2,
  },
  section: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  sectionHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 12,
    paddingVertical: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600" as const,
  },
  sectionTitleRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  option: {
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  themeOption: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
    flex: 1,
  },
  themeSwatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  optionText: {
    fontSize: 16,
    fontWeight: "500" as const,
  },
  booksSourceButton: {
    backgroundColor: "#D1FAE5",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    marginBottom: 12,
  },
  booksSourceButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#065F46",
  },
  myProjectsButton: {
    backgroundColor: "#DBEAFE",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  myProjectsButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#1E40AF",
  },
  contactDeveloperButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 12,
    marginTop: 12,
    gap: 10,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  contactDeveloperButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
  footerText: {
    fontSize: 14,
    marginTop: 16,
    textAlign: "center" as const,
    fontStyle: "italic" as const,
  },
  accountInfo: {
    fontSize: 14,
    textAlign: "center" as const,
    lineHeight: 20,
  },
  exportButton: {
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    marginBottom: 12,
  },
  exportButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
  },
  importButton: {
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    marginBottom: 12,
  },
  importButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
  },
  pickerContainer: {
    borderRadius: 12,
    borderWidth: 1,
    overflow: "hidden" as const,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  languageSelectButton: {
    minHeight: 52,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  languageSelectText: {
    fontSize: 16,
    flex: 1,
    marginRight: 8,
  },
  selectValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    marginRight: 8,
  },
  compactControlsGroup: {
    gap: 12,
  },
  compactSelectLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 2,
  },
  selectModalOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    marginRight: 8,
  },
  voiceModalInfo: {
    flex: 1,
    marginRight: 12,
  },
  languageModalCard: {
    width: '90%',
    maxWidth: 520,
    maxHeight: '75%',
    borderRadius: 16,
    borderWidth: 1,
    paddingTop: 16,
    paddingBottom: 12,
  },
  languageModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  languageModalList: {
    maxHeight: 380,
  },
  languageModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  languageModalItemText: {
    fontSize: 16,
    flex: 1,
    marginRight: 8,
  },
  languageModalCloseButton: {
    alignSelf: 'flex-end',
    marginTop: 12,
    marginRight: 12,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  languageModalCloseText: {
    fontWeight: '700',
    fontSize: 14,
  },
  picker: {
    height: 50,
    marginHorizontal: 4,
  },
  dyslexiaInfo: {
    fontSize: 14,
    lineHeight: 20,
    marginTop: 12,
    paddingHorizontal: 4,
  },
  sliderContainer: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  sliderLabel: {
    fontSize: 14,
    fontWeight: "600" as const,
    marginBottom: 8,
  },
  slider: {
    width: "100%",
    height: 40,
  },
  sliderDescription: {
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  resetButton: {
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    marginTop: 16,
    borderWidth: 2,
  },
  resetButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
  },
  resetScoreButton: {
    marginTop: 12,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
  },
  resetScoreButtonText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  resetScoreWarningText: {
    marginTop: 6,
    fontSize: 11,
    lineHeight: 16,
  },
  aboutButton: {
    backgroundColor: 'transparent',
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    marginTop: 12,
  },
  aboutButtonText: {
    fontSize: 16,
    fontWeight: "500" as const,
  },
  donateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 12,
    marginTop: 12,
    gap: 10,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  donateButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: "center" as const,
    alignItems: "center" as const,
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700" as const,
  },
  closeButton: {
    padding: 4,
  },
  modalBody: {
    gap: 8,
  },
  aboutLabel: {
    fontSize: 14,
    fontWeight: "600" as const,
    marginBottom: 4,
  },
  aboutValue: {
    fontSize: 18,
    fontWeight: "500" as const,
  },
  creditItem: {
    marginTop: 8,
  },
  creditLabel: {
    fontSize: 14,
    marginBottom: 2,
  },
  creditValue: {
    fontSize: 16,
    fontWeight: "500" as const,
    marginLeft: 16,
  },
  ttsSpeedContainer: {
    flexDirection: "row" as const,
    gap: 8,
    marginBottom: 12,
  },
  ttsSpeedOption: {
    flex: 1,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 6,
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
  },
  ttsSpeedText: {
    fontSize: 14,
    fontWeight: "600" as const,
  },
  voicesContainer: {
    gap: 8,
  },
  voiceOption: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
  },
  voiceInfo: {
    flex: 1,
    marginRight: 12,
  },
  voiceName: {
    fontSize: 14,
    fontWeight: "600" as const,
    flex: 1,
  },
  voiceNameRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
  },

  voiceLanguage: {
    fontSize: 12,
    marginTop: 2,
  },
  voiceActions: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  voiceTestButton: {
    padding: 8,
    borderRadius: 8,
  },
  voiceLoadingContainer: {
    padding: 16,
    borderRadius: 12,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 12,
  },
  voiceLoadingText: {
    fontSize: 14,
  },
  voiceEmptyContainer: {
    padding: 16,
    borderRadius: 12,
    alignItems: "center" as const,
  },
  voiceEmptyText: {
    fontSize: 14,
    textAlign: "center" as const,
  },
  customVersionButton: {
    padding: 14,
    borderRadius: 12,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    borderWidth: 2,
    marginTop: 12,
  },
  customVersionButtonText: {
    fontSize: 15,
    fontWeight: "600" as const,
  },
  customVersionDescription: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  faqButton: {
    padding: 12,
    borderRadius: 10,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    borderWidth: 1,
    marginBottom: 20,
  },
  faqButtonText: {
    fontSize: 14,
    fontWeight: "600" as const,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600" as const,
    marginBottom: 8,
  },
  urlInput: {
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    fontSize: 14,
    marginBottom: 16,
  },
  modalActionButton: {
    padding: 14,
    borderRadius: 10,
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    marginBottom: 12,
  },
  modalActionButtonText: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: "#fff",
  },
  divider: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
  },
  dividerText: {
    fontSize: 14,
    fontWeight: "500" as const,
  },
  moreThemesButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 6,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  premiumBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginLeft: 8,
  },
  timePickerButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    alignSelf: "flex-start" as const,
    marginTop: 8,
  },
  timePickerButtonText: {
    fontSize: 18,
    fontWeight: "700" as const,
    letterSpacing: 1,
  },
  timePickerDoneButton: {
    alignSelf: "flex-end" as const,
    marginTop: 12,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  timePickerDoneText: {
    fontWeight: "700" as const,
    fontSize: 14,
  },
  accountCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  accountCardRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 14,
  },
  accountAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  accountName: {
    fontSize: 17,
    fontWeight: "700" as const,
  },
  accountEmail: {
    fontSize: 13,
    marginTop: 2,
  },
  accountActionsRow: {
    flexDirection: "row" as const,
    gap: 10,
  },
  accountActionBtn: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  accountActionBtnText: {
    fontSize: 13,
    fontWeight: "600" as const,
  },
  accountHint: {
    fontSize: 13,
    marginTop: 10,
    textAlign: "center" as const,
    lineHeight: 18,
  },
  authOpenButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 10,
    padding: 16,
    borderRadius: 14,
  },
  authOpenButtonText: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: "#fff",
  },
  authInput: {
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    fontSize: 15,
    marginBottom: 10,
  },
  authSubmitButton: {
    padding: 15,
    borderRadius: 12,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginTop: 4,
  },
  authSubmitButtonText: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: "#fff",
  },
  authSwitchButton: {
    alignItems: "center" as const,
    paddingVertical: 12,
  },
  authSwitchText: {
    fontSize: 14,
    fontWeight: "500" as const,
  },
  authErrorBanner: {
    padding: 10,
    borderRadius: 10,
    marginBottom: 8,
  },
  authErrorText: {
    fontSize: 13,
    fontWeight: "500" as const,
    textAlign: "center" as const,
  },
  captchaLabel: {
    fontSize: 13,
    marginTop: -4,
    marginBottom: 8,
  },
  modeChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  modeChipText: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
});
